### ISSUE TITLE
I have installed Windows Universal Runtime version 10.0.22000.0, but I am prompted to upgrade my system

### ISSUE THREAD

**Issue by xiaodongYao** [microsoft/calculator#1878]
DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.22000.0 or later. You are currently running version 10.0.19043.1826. Update your OS or change the deployment target to a device with the appropriate version.

**Comment by denyaalt** [comment]
I have the same problem.  
Please post the compiled exe file.

**Comment by xiaodongYao** [comment]
> 

OK!,Thank you!!!!!

**Comment by xiaodongYao** [comment]
> I have the same problem. Please post the compiled exe file.

ok,thank you !

**Comment by clhenaqeeb** [comment]
Same issue here:
DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.22000.0 or higher. You currently are running version 10.0.19044.1889. Please update your OS, or change your deployment target to a device with the appropriate version.	Calculator

**Comment by clhenaqeeb** [comment]
Also the built app does not launch on win 10 and logs these in the event viewer:

Application: CalculatorApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e0434352, exception address 00007FFAA0754FD9
Stack:

**Followed by:**

Faulting application name: CalculatorApp.exe, version: 0.0.0.0, time stamp: 0x630fff6b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1889, time stamp: 0xe9ede6d6
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0x2218
Faulting application start time: 0x01d8bdb164444cad
Faulting application path: C:\Users\clhenaqeeb\source\repos\calculator\src\x64\Debug\Calculator\CalculatorApp.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 95660539-6ba6-40b5-bdfd-b6841dcf46eb
Faulting package full name: 
Faulting package-relative application ID: 

**Followed by: (Error reporting)**

Fault bucket 1772086560930812384, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: CalculatorApp.exe
P2: 0.0.0.0
P3: 630fff6b
P4: KERNELBASE.dll
P5: 10.0.19041.1889
P6: e9ede6d6
P7: e0434352
P8: 0000000000034fd9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER44C6.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4553.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4573.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4571.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER45C1.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CalculatorApp.ex_8b8e0d527a6ef764d465c738fbad2d612d3d_d78ac851_9d267b7a-27ee-4875-a0bc-b6db57c9eafc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 95660539-6ba6-40b5-bdfd-b6841dcf46eb
Report Status: 268435456
Hashed bucket: fa267d4ffd8acfb12897b756978651e0
Cab Guid: 0

**Comment by mcooley** [comment]
It is expected that on Windows 10 builds, you may be able to build the project but you won't be able to run the app without modifications. In #1893, I've updated the README to clarify this.
