### ISSUE TITLE
Mismatch between application language and system language

### ISSUE THREAD

**Issue by Goo-aw233** [microsoft/calculator#1987]
**Describe the bug**
My system language is Simplified Chinese, but the language in the calculator is English

**Steps To Reproduce**
No steps to reproduce
:(

**Expected behavior**
Under normal circumstances, the language of the calculator should vary with the system language

**Screenshots**
![image](https://user-images.githubusercontent.com/91338751/226094664-afcec7f4-76fb-4c58-9c04-946a337b811c.png)

**Device and Application Information**
 - OS Build:Windows 11 Insider Preview 25314.1010
 - Architecture:x86_64
 - Application Version:11.2210.0.0
 - Region:zh-CN
 - Dev Version Installed:False

**Requested Assignment**
If possible, I would like to fix this.

**Comment by lazydevl0per** [comment]
I have looked at the relevant .xaml and resource files and the [NavCategory](https://github.com/microsoft/calculator/blob/main/src/CalcViewModel/Common/NavCategory.h) class. Translations should be working the way everything is implemented on the main branch.

Additionally i have checked out the source code and built the calculator App. I've tried out a few languages and it is translated on my machine.

OS: Windows 11 Pro 10.0.22621
Architecture: x86_64

Can this be an OS related problem? I see you're running Insider Preview builds.

**Comment by mcooley** [comment]
This does look like an issue with app installation in Windows rather than an issue with the app itself.

Calculator's translations are split into separate resource packages, one for each language. If your system has only English packages installed and then you switch your preferred language to Simplified Chinese, Windows will need to download Calculator's Simplified Chinese package from the Store. There are many reasons this background download might not happen: the Store has not yet checked for updates and you need to wait a bit longer, there's an issue with your internet connection, there are policies configured to disable Store updates, etc.

If you're still experiencing this issue, please report it the Feedback Hub app. That will give the Windows app installation experts the opportunity to take a look.
